version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: quiz-postgres
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    networks:
      - quiz-network

  pgadmin:
    image: dpage/pgadmin4:latest  
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "82:80"
    networks:
      - quiz-network
    depends_on:
      - postgres

networks:
  quiz-network:
    driver: bridge